version: 2
jobs:
  build:
    working_directory: ~/tweek-clients

    environment:
      NODE_ENV: development

    docker:
      - image: node:8.5.0
    
    steps:
      - checkout

      - setup_remote_docker:
          reusable: true

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
            curl -L -o /usr/bin/docker-compose "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)"
            chmod +x /usr/bin/docker-compose

      - run:
          name: Build client containers
          command: |
            docker build -t js_tests .
            docker build -t dotnet_tests ./dotnet

      - run: 
          name: Run environment
          command: |
            docker pull soluto/tweek-blackbox:latest
            docker run -d -e API_PORT=1111 --rm -v=/var/run/docker.sock:/var/run/docker.sock -v=/$(pwd)/testRepoData/:/repo soluto/tweek-blackbox:latest
      
      - run: 
          name: Test js clients
          command: |
            docker ps
            docker run --network=blackbox_default -e TWEEK_LOCAL_API=http://api js_tests