version: 2
jobs:
  test_js:
    working_directory: ~/tweek-clients
    environment:
      NODE_ENV: development
    
    machine: true

    steps:
      - checkout

      - run:
          name: Build client containers
          command: docker build -t js_tests .

      - run: 
          name: Run environment
          command: |
            docker pull soluto/tweek-blackbox:latest
            docker run -d -v=/var/run/docker.sock:/var/run/docker.sock -v=/$(pwd)/testRepoData/:/repo soluto/tweek-blackbox:latest

      - run: 
          name: Test js clients
          command: |
            sleep 70
            docker run --network=blackbox_default -e TWEEK_LOCAL_API=http://api js_tests

  test_dotnet:
    working_directory: ~/tweek-clients
    environment:
      NODE_ENV: development
    
    machine: true
    steps:
      - checkout

      - run:
          name: Build client containers
          command: docker build -t dotnet_tests ./dotnet
    - run: 
          name: Run environment
          command: |
            docker pull soluto/tweek-blackbox:latest
            docker run -d -v=/var/run/docker.sock:/var/run/docker.sock -v=/$(pwd)/testRepoData/:/repo soluto/tweek-blackbox:latest

    - run:
          name: Test dotnet client
          command: |
            docker run -d --network=blackbox_default -e TWEEK_LOCAL_API=http://api dotnet_tests
            docker ps
            docker exec -e "VersionSuffix=0.2.$CIRCLE_BUILD_NUM" $(docker ps|grep dotnet_tests|cut -d" " -f1) /bin/bash -c "cd /test-environment/ && dotnet build -c release"
            docker exec -e "VersionSuffix=0.2.$CIRCLE_BUILD_NUM" $(docker ps|grep dotnet_tests|cut -d" " -f1) /bin/bash -c "cd /test-environment/Tweek.Client.Tests && dotnet test"



  #deploy:

workflows:
  version: 2
  test_deploy:
    jobs:
      - test_js
      - test_dotnet
      #- deploy