version: 2
jobs:
  build:
    working_directory: ~/tweek-clients
    environment:
      NODE_ENV: development
    
    machine: true

    steps:
      - checkout

      - run:
          name: Run JS tests
          command: docker-compose -p blackbox up --exit-code-from js_tests js_tests

      - deploy: 
          name: npm
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              if [[ $(node -p -e "require('./js/tweek-client/package.json').version") != $(npm show tweek-client version) ]]; then
                echo "publish tweek-client"
                cd js/tweek-client && yarn && npm run build && npm publish && cd ../..
              fi
              if [[ $(node -p -e "require('./js/tweek-local-cache/package.json').version") != $(npm show tweek-local-cache version) ]]; then
                echo "publish tweek-local-cache"
                cd js/tweek-client && yarn && npm run build && cd ../..
                cd js/tweek-local-cache && yarn && npm run build && npm publish && cd ../..
              fi
              if [[ $(node -p -e "require('./js/react-tweek/package.json').version") != $(npm show react-tweek version) ]]; then
                echo "publish react-tweek"
                cd js/react-tweek && yarn && npm run build && npm publish && cd ../..
              fi
            else 
              echo "not deploying on non master branches"
            fi

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      #- test
      #- deploy