version: 2
jobs:
  build:
    working_directory: ~/tweek-clients
    environment:
      NODE_ENV: development
    
    machine: true

    steps:
      - checkout

      - run: 
          name: Run environment
          command: |
            docker pull soluto/tweek-blackbox:latest
            docker run -d -v=/var/run/docker.sock:/var/run/docker.sock -v=/$(pwd)/testRepoData/:/repo soluto/tweek-blackbox:latest
  #test:

  #deploy:

workflows:
  version: 2
  build_test_deploy:
    - build
    #- test
    #- deploy